package S3E4P1;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class PhuongTrinhBacNhat_UI extends javax.swing.JFrame {   

    /**
     * Creates new form PhuongTrinhBacNhat_IU
     */
    public PhuongTrinhBacNhat_UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_a = new javax.swing.JTextField();
        txt_b = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lb_pt = new javax.swing.JLabel();
        lb_kq = new javax.swing.JLabel();
        bt_xpt = new javax.swing.JButton();
        bt_gpt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giải phương trình bậc nhất một ẩn");

        jLabel1.setText("Nhập a:");

        jLabel2.setText("Nhập b:");

        jLabel3.setText("Phương trình:");

        jLabel4.setText("Kết quả:");

        lb_pt.setText("pt");

        lb_kq.setText("kq");

        bt_xpt.setText("Xem phương trình");
        bt_xpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xptActionPerformed(evt);
            }
        });

        bt_gpt.setText("Giải phương trình");
        bt_gpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_gptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_pt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_kq, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_a, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(txt_b))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_gpt)
                            .addComponent(bt_xpt))
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_xpt))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_gpt))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lb_pt))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lb_kq))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        txt_a.getAccessibleContext().setAccessibleName("txt_a");
        txt_b.getAccessibleContext().setAccessibleName("txt_b");
        lb_pt.getAccessibleContext().setAccessibleName("lb_pt");
        lb_kq.getAccessibleContext().setAccessibleName("lb_kq");
        bt_xpt.getAccessibleContext().setAccessibleName("bt_pt");
        bt_gpt.getAccessibleContext().setAccessibleName("bt_kq");

        getAccessibleContext().setAccessibleName("ptbn");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_xptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xptActionPerformed
        int a = Integer.parseInt(txt_a.getText());
        int b = Integer.parseInt(txt_b.getText());
        PhuongTrinhBacNhat pt = new PhuongTrinhBacNhat(a, b);  
        if (pt.KiemTra() == true){      
            lb_pt.setText(pt.toString());
        }
        else
            lb_pt.setText("Lỗi nhập dữ liệu!");
        
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bt_xptActionPerformed

    private void bt_gptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_gptActionPerformed
        int a = Integer.parseInt(txt_a.getText());
        int b = Integer.parseInt(txt_b.getText());
        PhuongTrinhBacNhat pt = new PhuongTrinhBacNhat(a, b);  
        if (pt.KiemTra() == true){      
            lb_kq.setText("x = "+pt.GiaiPT());
        }
        else
            lb_kq.setText("Lỗi nhập dữ liệu!");
    }//GEN-LAST:event_bt_gptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhuongTrinhBacNhat_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhuongTrinhBacNhat_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhuongTrinhBacNhat_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhuongTrinhBacNhat_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PhuongTrinhBacNhat_UI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_gpt;
    private javax.swing.JButton bt_xpt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lb_kq;
    private javax.swing.JLabel lb_pt;
    private javax.swing.JTextField txt_a;
    private javax.swing.JTextField txt_b;
    // End of variables declaration//GEN-END:variables
}
