/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package W3E1P1;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class productTimKiem extends javax.swing.JFrame {

    /**
     * Creates new form productTimKiem
     */
    private Product p[];
    private int k;
    public productTimKiem(Product p[],int k) {
        initComponents();
        this.k=k;
        this.p=p;
        v_header.add("Product");
        v_header.add("Number");
        v_header.add("Price");
        v_header.add("Company");
        v_header.add("Sell");
        dtm.setDataVector(v_content, v_header);
        tb_timkiem.setModel(dtm);
    }

    private productTimKiem() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbb = new javax.swing.JComboBox<>();
        bt_timkiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_timkiem = new javax.swing.JTable();
        bt_exit = new javax.swing.JButton();
        txt_timkiem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TimKiem_UI");

        jLabel1.setText("Tìm kiếm:");

        cbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Product", "Number", "Price", "Company" }));

        bt_timkiem.setText("Tìm kiếm");
        bt_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_timkiemActionPerformed(evt);
            }
        });

        tb_timkiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_timkiem);

        bt_exit.setText("Exit");
        bt_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(bt_timkiem))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bt_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(cbb, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_timkiem)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_timkiem)
                    .addComponent(bt_exit))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_exitActionPerformed
        // TODO add your handling code here:
        this.toBack();
    }//GEN-LAST:event_bt_exitActionPerformed

    DefaultTableModel dtm=new DefaultTableModel();
    Vector v_header=new Vector();
    Vector v_content=new Vector();
    private void bt_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_timkiemActionPerformed
        // TODO add your handling code here:
        
        if("Product".equals((String) cbb.getSelectedItem())){
            dtm.setNumRows(0);
            for(int i=0;i<k;i++){
                if(p[i].getName().equals(txt_timkiem.getText())){
                    Vector v_record=new Vector();
                    v_record.add(p[i].getName());
                    v_record.add(p[i].getNumber());
                    v_record.add(p[i].getPrice());
                    v_record.add(p[i].getNameC());
                    v_record.add(p[i].Sell_produc());
                    v_content.add(v_record);
                    dtm.setDataVector(v_content, v_header);
                }
            }
        }
        else if("Number".equals((String) cbb.getSelectedItem())){
            dtm.setNumRows(0);
            for(int i=0;i<k;i++){
                if(p[i].getNumber()==Integer.parseInt(txt_timkiem.getText())){
                    Vector v_record=new Vector();
                    v_record.add(p[i].getName());
                    v_record.add(p[i].getNumber());
                    v_record.add(p[i].getPrice());
                    v_record.add(p[i].getNameC());
                    v_record.add(p[i].Sell_produc());
                    v_content.add(v_record);
                    dtm.setDataVector(v_content, v_header);
                }
            }
        }
        else if("Price".equals((String) cbb.getSelectedItem())){
            dtm.setNumRows(0);
            for(int i=0;i<k;i++){
                if(p[i].getPrice()==Integer.parseInt(txt_timkiem.getText())){
                    Vector v_record=new Vector();
                    v_record.add(p[i].getName());
                    v_record.add(p[i].getNumber());
                    v_record.add(p[i].getPrice());
                    v_record.add(p[i].getNameC());
                    v_record.add(p[i].Sell_produc());
                    v_content.add(v_record);
                    dtm.setDataVector(v_content, v_header);
                }
            }
        
        }
        else if("Company".equals((String) cbb.getSelectedItem())){
            dtm.setNumRows(0);
            for(int i=0;i<k;i++){
                if(p[i].getNameC().equals(txt_timkiem.getText())){
                    Vector v_record=new Vector();
                    v_record.add(p[i].getName());
                    v_record.add(p[i].getNumber());
                    v_record.add(p[i].getPrice());
                    v_record.add(p[i].getNameC());
                    v_record.add(p[i].Sell_produc());
                    v_content.add(v_record);
                    dtm.setDataVector(v_content, v_header);
                }
            }
            
        }
    }//GEN-LAST:event_bt_timkiemActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productTimKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productTimKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productTimKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productTimKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productTimKiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_exit;
    private javax.swing.JButton bt_timkiem;
    private javax.swing.JComboBox<String> cbb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_timkiem;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables
}
